apiVersion: v1
kind: Pod
metadata:
  name: django-todo-pod
  namespace: django-todo-app
spec:
  containers:
    - name: django-todo-ctr
      image: awsstudy911/todo-app:latest
      ports:
        - containerPort: 8001


# Note: its not able to take my image from my rege, while its taking shubham's regestry

     
